server:
  port: 9001
spring:
  application:
    name: user-auth
  redis:
    host: 118.25.242.174
    port: 6370
    #Redis数据库索引（默认为0）
    database: 0
    #连接超时时间（毫秒）
    timeout: 1800000
    password: yourpasswd
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://118.25.242.174:3310/hotel_oauth?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true&serverTimezone=UTC
    username: root
    password: 123456

  main:
    allow-bean-definition-overriding: true
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka



index:
  ribbon:
    ReadTimeout: 60000
    ConnectTimeout: 60000

auth:
#  ttl: 600  #token存储到redis的过期时间
  clientId: hoteloau
  clientSecret: hoteloau
#  cookieDomain: localhost
  cookieDomain: nsvpy051.dongtaiyuming.net
#  cookieDomain: zerongweb.free.idcfengye.com
  cookieMaxAge: 7200

#证书和密钥配置
encrypt:
  key-store:
    #证书路径
    location: classpath:/hoteloau.jks
    #密钥-别名-证书密码
    secret: hoteloau
    alias: hoteloau
    password: hoteloau
#token在redis存储时长（毫秒）
token:
  #60*60*2*1000
  accessTokenTime: 7200000
  #24*60*60*5*1000
  refreshTokenTime: 432000000


