# Tomcat
server:
  # 端 口
  port: 10012
  # Servlet

#eureka配置
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka
  instance:
    prefer-ip-address: true
feign:
  #hystrix 配置
  hystrix:
    command:
      default:
        execution:
          isolation:
            thread:
              timeoutInMilliseconds: 10000
            strategy: SEMAPHORE

# Spring 配置
spring:
  thymeleaf:
    cache: false
  application:
    name: wx-index
  main:
    allow-bean-definition-overriding: true







